with public_directory(name, type, city) as (
  values
    ('Pharmacie de l''Aeroport', 'pharmacy', 'Yoff'),
    ('Pharmacie Mouhamadou El Hamid Almadies', 'pharmacy', 'Almadies'),
    ('Pharmacie As Salihou', 'pharmacy', 'Dakar'),
    ('Pharmacie Baye Issa', 'pharmacy', 'Dakar'),
    ('Clinique Alhamdoulilah', 'clinic', 'Dakar'),
    ('Clinique KOTI', 'clinic', 'Dakar'),
    ('Clinique Maryam', 'clinic', 'Dakar'),
    ('Clinique Maimouna Toure (CMT)', 'clinic', 'Dakar'),
    ('Institut d''Hygiene Sociale - Polyclinique', 'hospital', 'Dakar-Plateau'),
    ('Hopital Youssou Mbargane Diop', 'hospital', 'Rufisque'),
    ('Hopital Roi Baudouin', 'hospital', 'Guediawaye'),
    ('Hopital psychiatrique de Thiaroye', 'hospital', 'Thiaroye'),
    ('Hopital Principal de Dakar', 'hospital', 'Dakar-Plateau'),
    ('Hopital Militaire de Ouakam', 'hospital', 'Ouakam'),
    ('Hopital Masroor', 'hospital', 'Dakar'),
    ('Hopital Idrissa Pouye', 'hospital', 'Grand-Yoff'),
    ('Hopital d''Enfants de Diamniadio', 'hospital', 'Diamniadio'),
    ('Hopital de Pikine', 'hospital', 'Pikine'),
    ('Hopital Dalal Jamm', 'hospital', 'Guediawaye'),
    ('Hopital Aristide Le Dantec', 'hospital', 'Dakar-Plateau'),
    ('Centre hospitalier universitaire de Fann', 'hospital', 'Fann'),
    ('Centre hospitalier Abass Ndao', 'hospital', 'Dakar'),
    ('Centre de traitement ambulatoire du CHNU de Fann', 'hospital', 'Fann'),
    ('CS Wahinane Guediawaye', 'health_center', 'Guediawaye'),
    ('CS Tivaouane Peulh', 'health_center', 'Tivaouane Peulh'),
    ('CS Sheikh Khalifa Bin Hamad Al Thiani (CS Yeumbeul)', 'health_center', 'Yeumbeul'),
    ('CS Seydina Issa Rohou Lahi (CS Camberene)', 'health_center', 'Camberene'),
    ('CS Sangalkam', 'health_center', 'Sangalkam'),
    ('CS SAMU municipal', 'health_center', 'Dakar'),
    ('CS Rufisque Polyclinique', 'health_center', 'Rufisque'),
    ('CS Plateau', 'health_center', 'Dakar-Plateau'),
    ('CS Philippe Maguilen Senghor', 'health_center', 'Yoff'),
    ('CS Ouakam', 'health_center', 'Ouakam'),
    ('CS Ndiaye Diouf (CS Bargny)', 'health_center', 'Bargny'),
    ('CS Nabil Choucair', 'health_center', 'Dakar'),
    ('CS Mutuelle de Rufisque', 'health_center', 'Rufisque'),
    ('CS maternel et infantile', 'health_center', 'Dakar'),
    ('CS Mamadou Diop (CS Liberte 6)', 'health_center', 'Liberte 6'),
    ('CS Le Technopole', 'health_center', 'Pikine'),
    ('CS Khadimoul Rassoul (CS Mbao)', 'health_center', 'Mbao'),
    ('CS Keur Massar', 'health_center', 'Keur Massar'),
    ('CS HLM', 'health_center', 'HLM'),
    ('CS Hann-sur-Mer', 'health_center', 'Hann'),
    ('CS Hann Maristes', 'health_center', 'Hann'),
    ('CS Grand Dakar', 'health_center', 'Grand Dakar'),
    ('CS Golf Sud', 'health_center', 'Guediawaye'),
    ('CS Gaspard Camara', 'health_center', 'Dakar'),
    ('CS Fondation Elizabeth Diouf', 'health_center', 'Dakar'),
    ('CS Elisabeth Diouf', 'health_center', 'Dakar'),
    ('CS du district sanitaire de Yeumbeul', 'health_center', 'Yeumbeul'),
    ('CS du district sanitaire de Guediawaye', 'health_center', 'Guediawaye'),
    ('CS Diogali Mousse Samb (CS Ngor)', 'health_center', 'Ngor'),
    ('CS Diamniadio', 'health_center', 'Diamniadio'),
    ('CS communautaire Awa Marie Coll Seck', 'health_center', 'Dakar'),
    ('CS Colobane', 'health_center', 'Colobane'),
    ('CS Cheikh A. Bamba (PMI Medina)', 'health_center', 'Medina'),
    ('CS Baye Talla Diop', 'health_center', 'Dakar'),
    ('CS Aristide Mensah', 'health_center', 'Dakar'),
    ('CS Annette Mbaye d''Erneville', 'health_center', 'Ouakam'),
    ('CS Abdou Aziz Sy Dabakh', 'health_center', 'Dakar'),
    ('Centre national de transfusion sanguine', 'health_center', 'Fann'),
    ('Centre national d''appareillage orthopedique', 'health_center', 'Dakar'),
    ('Centre medical Ademis', 'health_center', 'Dakar'),
    ('Centre international de cancerologie', 'health_center', 'Dakar'),
    ('Centre d''hemodialyse de Dakar', 'health_center', 'Dakar'),
    ('Centre de geriatrie et de gerontologie', 'health_center', 'Dakar'),
    ('Centre de sante de Bopp', 'health_center', 'Bopp'),
    ('Centre antidiabete Marc Sankale', 'health_center', 'Dakar'),
    ('PS Yoff Tonghor', 'other', 'Yoff'),
    ('PS Yoff Ndenatte', 'other', 'Yoff'),
    ('PS Yeumbeul Nord', 'other', 'Yeumbeul'),
    ('PS Yeumbeul Diamalaye', 'other', 'Yeumbeul'),
    ('PS Yene', 'other', 'Yene'),
    ('PS Yeba', 'other', 'Dakar'),
    ('PS Wayambam', 'other', 'Dakar'),
    ('PS Touba Diacksao', 'other', 'Thiaroye'),
    ('PS Tonghor', 'other', 'Yoff'),
    ('PS Tivaouane Peulh', 'other', 'Tivaouane Peulh'),
    ('PS Thiawlene', 'other', 'Rufisque'),
    ('PS Thiaroye-sur-Mer', 'other', 'Thiaroye'),
    ('PS Thiaroye Minam', 'other', 'Thiaroye'),
    ('PS Thiaroye Gare', 'other', 'Thiaroye'),
    ('PS Thiaroye Azur', 'other', 'Thiaroye'),
    ('PS Tawfekh', 'other', 'Dakar'),
    ('PS Sonatel Malika', 'other', 'Malika'),
    ('PS Sokhna Safietou Laye Niang (Yeumbeul Sud)', 'other', 'Yeumbeul'),
    ('PS Serigne Saliou Mbacke (Darou Rahmane 2)', 'other', 'Dakar'),
    ('PS Sendou', 'other', 'Sendou'),
    ('PS Seby Ponty', 'other', 'Sebikotane'),
    ('PS Sebikotane', 'other', 'Sebikotane'),
    ('PS Sant Yalla', 'other', 'Dakar'),
    ('PS Sandial', 'other', 'Dakar'),
    ('PS Sam Sam 3', 'other', 'Guediawaye'),
    ('PS Raffenel', 'other', 'Dakar'),
    ('PS du Port', 'other', 'Dakar-Plateau'),
    ('PS Petit Mbao', 'other', 'Mbao'),
    ('PS Pepiniere', 'other', 'Dakar'),
    ('PS Omar Mbassou Niang U16', 'other', 'Dakar'),
    ('PS Norade', 'other', 'Dakar'),
    ('PS Toubab Dialaw', 'other', 'Toubab Dialaw'),
    ('PS Unite 22', 'other', 'Guediawaye'),
    ('PS Unite 26', 'other', 'Guediawaye'),
    ('PS Unite 4', 'other', 'Guediawaye'),
    ('PS Unite 8', 'other', 'Guediawaye'),
    ('PS Unite 9', 'other', 'Guediawaye'),
    ('PS Nimzatt', 'other', 'Guediawaye'),
    ('PS Nianghal', 'other', 'Dakar'),
    ('PS Niague', 'other', 'Niague'),
    ('PS Niacoul Rab', 'other', 'Rufisque'),
    ('PS Nguinaw Rail Sud', 'other', 'Pikine')
), normalized as (
  select
    (
      substr(md5('santemap|' || name || '|' || city), 1, 8) || '-' ||
      substr(md5('santemap|' || name || '|' || city), 9, 4) || '-' ||
      substr(md5('santemap|' || name || '|' || city), 13, 4) || '-' ||
      substr(md5('santemap|' || name || '|' || city), 17, 4) || '-' ||
      substr(md5('santemap|' || name || '|' || city), 21, 12)
    )::uuid as id,
    name,
    type::public.health_structure_type as type,
    city
  from public_directory
)
insert into public.health_structures (
  id,
  owner_user_id,
  name,
  type,
  address,
  city,
  region,
  phone_landline,
  phone_mobile,
  email,
  manager_name,
  description,
  verified
)
select
  id,
  '00000000-0000-0000-0000-000000000001'::uuid,
  name,
  type,
  case when city = 'Dakar' then 'Region de Dakar' else city || ', region de Dakar' end,
  city,
  'Dakar',
  '',
  null,
  '',
  'Repertoire public AYMANE',
  'Structure repertoriee publiquement. Confirmez les coordonnees et horaires avant de vous deplacer.',
  true
from normalized
on conflict (id) do update set
  name = excluded.name,
  type = excluded.type,
  address = excluded.address,
  city = excluded.city,
  region = excluded.region,
  manager_name = excluded.manager_name,
  description = excluded.description,
  verified = true,
  updated_at = now();
